FROM golang:1.18-alpine as builder
WORKDIR /app
COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY main.old.go ./main.go
RUN go build -o /main

FROM alpine:3.15
COPY --from=builder /main /main
EXPOSE 8080
CMD ["/main"]
